import type { Company } from '@/types';

// This is mock data. In a real application, this would be fetched
// from a database that is populated by the Boycott List Summarizer.
const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'HP (Hewlett Packard)',
    category: 'Technology',
    involvement: 'Provides technology and services to the Israeli military and illegal settlements.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'hp',
  },
  {
    id: '2',
    name: 'Siemens',
    category: 'Industrial',
    involvement: 'Involved in the construction of the Euro-Asia Interconnector, which links Israel\'s electricity grid with Europe\'s, crossing through illegal settlements.',
    subCompanies: 'N/A',
    country: 'Germany',
    logo: 'siemens',
  },
  {
    id: '3',
    name: 'Puma',
    category: 'Apparel',
    involvement: 'Sponsors the Israel Football Association, which includes teams in illegal Israeli settlements on Palestinian land.',
    subCompanies: 'N/A',
    country: 'Germany',
    logo: 'puma',
  },
  {
    id: '4',
    name: 'AXA',
    category: 'Finance',
    involvement: 'Invests in Israeli banks that finance the theft of Palestinian land and natural resources.',
    subCompanies: 'N/A',
    country: 'France',
    logo: 'axa',
  },
  {
    id: '5',
    name: 'SodaStream',
    category: 'Food & Beverage',
    involvement: 'Actively complicit in Israel\'s policy of displacing the indigenous Bedouin-Palestinian citizens of Israel in the Naqab (Negev).',
    subCompanies: 'N/A',
    country: 'Israel',
    logo: 'sodastream',
  },
  {
    id: '6',
    name: "McDonald's",
    category: 'Food & Beverage',
    involvement: 'Israeli franchise provided free meals to the Israeli military.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'mcdonalds',
  },
  {
    id: '7',
    name: 'Burger King',
    category: 'Food & Beverage',
    involvement: 'Israeli franchise provided free meals to Israeli soldiers.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'burger king',
  },
   {
    id: '8',
    name: 'Starbucks',
    category: 'Food & Beverage',
    involvement: 'Sued its workers\' union, Starbucks Workers United, over a pro-Palestine post.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'starbucks',
  },
  {
    id: '9',
    name: 'Google & Amazon',
    category: 'Technology',
    involvement: 'Involved in Project Nimbus, a $1.2B contract to provide cloud services to the Israeli government and military.',
    subCompanies: 'Alphabet, AWS',
    country: 'USA',
    logo: 'google amazon',
  },
  {
    id: '10',
    name: 'Chevron',
    category: 'Energy',
    involvement: 'Extracting gas claimed by Israel in the Eastern Mediterranean, generating billions in revenue for Israel.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'chevron',
  },
  {
    id: '11',
    name: 'Intel',
    category: 'Technology',
    involvement: 'Announced a new $25 billion investment in Israel in June 2023. Runs a large R&D center in Israel.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'intel',
  },
  {
    id: '12',
    name: 'IBM',
    category: 'Technology',
    involvement: 'Provides services to the Israeli Population and Immigration Authority, and has a large R&D center in Israel.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'ibm',
  },
  {
    id: '13',
    name: 'Coca-Cola',
    category: 'Food & Beverage',
    involvement: 'Operates a factory in the illegal Israeli settlement of Atarot.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'coca cola',
  },
  {
    id: '14',
    name: 'Sabra',
    category: 'Food & Beverage',
    involvement: 'Jointly owned by PepsiCo and Strauss Group, which provides financial support to the Israeli military.',
    subCompanies: 'PepsiCo, Strauss Group',
    country: 'USA',
    logo: 'sabra hummus',
  },
  {
    id: '15',
    name: 'Caterpillar',
    category: 'Industrial',
    involvement: 'Sells bulldozers and other equipment to the Israeli military, which are used to demolish Palestinian homes and infrastructure.',
    subCompanies: 'N/A',
    country: 'USA',
    logo: 'caterpillar',
  },
];

export async function getBoycottList(): Promise<Company[]> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return mockCompanies;
}
